services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend/study/
    ports:
      - "4000:4000"
    volumes:
      - ./backend/study:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/study/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/study:/app
    depends_on:
      - backend

volumes:
  db_data:
  deps_data:
  node_modules_data:
